name: Update Latest Blog Posts

on:
  workflow_dispatch:
  # for trigger via webhooks
  repository_dispatch:
    types: [trigger]

jobs:
  update-posts:
    runs-on: ubuntu-latest
    name: Update Posts

    steps:
        - name: Checkout profile repo
          uses: actions/checkout@v4

        - name: Checkout blog-posts repo
          uses: actions/checkout@v4
          with:
            repository: backpackerhh/blog-posts
            path: .blog-posts
            ref: main

        - name: Update README with latest posts
          uses: backpackerhh/github-latest-blog-posts@main
          with:
            POSTS_DIR: .blog-posts
