name: Update Recent Activity

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  schedule:
    # 8:00 and 20:00 every day
    - cron: "0 8,20 * * *"
  workflow_dispatch:

jobs:
  generate-feed:
    runs-on: ubuntu-latest
    name: Update Activity

    steps:
      - uses: actions/checkout@v6
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          MAX_LINES: 5
